### ISSUE TITLE
feature request: middleware and software packs

### ISSUE THREAD

**Issue by lunarifish** [patrislav1/cubemx.cmake#18]
It seems like the parser doesn't care about middlewares(freertos, usb_device, etc.). As this project is a "minimal" ioc parser, is it OK to take care of these additional components?

Or alternatively, can we add a `.cproject` parser, and directly extract sources/include paths from CubeIDE project file?

**Comment by patrislav1** [comment]
see also [caveats](https://github.com/patrislav1/cubemx.cmake?tab=readme-ov-file#caveats), 4th point. (with example how to add such things manually).

this project is supposed to be simple / lightweight, so at the moment I consider this out of scope.
