### ISSUE TITLE
CubeMX compiler settings were not created / considered

### ISSUE THREAD

**Issue by marco-polo-github** [patrislav1/cubemx.cmake#3]
Hello, I successfully compiled a HelloWorld project out of CubeMX with cmake after using your scripts with a recent sample Nucleo board Nucleo-U575ZI.
Therefore I had to adapt the cubemx-cmake.py in terms of coreTable and fpuTable. In my opinion the compiler options are already visible in the settings of CubeMX -> C/C++ Build -> MCU GCC Compiler -> All options 

Would it be feasible to read out that information from the project instead of manual creating this tables? I also noticed the compiler / linker switches were not put 1:1 to the cmake files, so my result elf-binary is slightly different. 

This idea (and also my low Python skills) snarled me up sending you a table change commit. 
What do you think? Or do I miss something?
Best Regards.

**Comment by patrislav1** [comment]
I haven't kept up with new STM32 chips and recent CubeMX versions tbh. Does CubeMX save compiler settings in the project file now? Then it would be smarter indeed to reuse them.

**Comment by marco-polo-github** [comment]
I just did a text search for the compiler flags and it is not as easy as I thought. The active build configuration needs to be considered first (e.g. Debug or Release or whatever).
Then the compiler settings are saved in the configuration e.g.: > HelloWorld/Debug/makefile
In this file there is a main-build Target defined and below the "Tool invocations" where the settings for the elf file is set. There it can be fiddled out.

**Comment by patrislav1** [comment]
So the compiler flags can still not be retrieved from the project file and we'll have to maintain our lookup tables for them.

Can you make a PR for the table updates (or, alternatively, just put your updated table in a gist)?

**Comment by marco-polo-github** [comment]
So you think the build configuration is not always there? This is my > HelloWorld/Debug/makefile:

\# Tool invocations
HelloWorld_nucleo.elf: $(OBJS) $(USER_OBJS) C:\Users\test\STM32CubeIDE\workspace_1.7.0\HelloWorld\STM32U575ZITXQ_FLASH.ld makefile objects.list $(OPTIONAL_TOOL_DEPS)
	arm-none-eabi-gcc -o "HelloWorld_nucleo.elf" @"objects.list" $(USER_OBJS) $(LIBS) **-mcpu=cortex-m33** -T"C:\Users\test\STM32CubeIDE\workspace_1.7.0\HelloWorld\STM32U575ZITXQ_FLASH.ld" --specs=nosys.specs -Wl,-Map="HelloWorld_nucleo.map" -Wl,--gc-sections -static --specs=nano.specs **-mfpu=fpv5-sp-d16** -mfloat-abi=hard -mthumb -Wl,--start-group -lc -lm -Wl,--end-group
	@echo 'Finished building target: $@'
	@echo ' '

**Comment by patrislav1** [comment]
Pls also post your .ioc file (using the ` ``` ` Markdown tag for code)

**Comment by marco-polo-github** [comment]
Pulls request I can do of course, but I can just show that here too. I haven't done that with the gist. 

This is the generated .ioc file:
`#MicroXplorer Configuration settings - do not modify
ADC1.CommonPathInternal=null|null|null|null
ADC1.IPParameters=master,NbrOfConversion,Resolution,CommonPathInternal
ADC1.NbrOfConversion=1
ADC1.Resolution=ADC_RESOLUTION_14B
ADC1.master=1
CORTEX_M33_NS.userName=CORTEX_M33
File.Version=6
GPIO.groupedBy=Group By Peripherals
KeepUserPlacement=false
Mcu.ContextProject=TrustZoneDisabled
Mcu.Family=STM32U5
Mcu.IP0=ADC1
Mcu.IP1=CORTEX_M33_NS
Mcu.IP2=DEBUG
Mcu.IP3=NVIC
Mcu.IP4=PWR
Mcu.IP5=RCC
Mcu.IP6=SYS
Mcu.IPNb=7
Mcu.Name=STM32U575ZITxQ
Mcu.Package=LQFP144
Mcu.Pin0=PC13
Mcu.Pin1=PC14-OSC32_IN (PC14)
Mcu.Pin10=PA11
Mcu.Pin11=PA12
Mcu.Pin12=PA13 (JTMS/SWDIO)
Mcu.Pin13=PA14 (JTCK/SWCLK)
Mcu.Pin14=PA15 (JTDI)
Mcu.Pin15=PB3 (JTDO/TRACESWO)
Mcu.Pin16=PB5
Mcu.Pin17=PB7
Mcu.Pin18=VP_PWR_VS_DBSignals
Mcu.Pin19=VP_PWR_VS_SECSignals
Mcu.Pin2=PC15-OSC32_OUT (PC15)
Mcu.Pin20=VP_SYS_VS_Systick
Mcu.Pin3=PC2
Mcu.Pin4=PB14
Mcu.Pin5=PB15
Mcu.Pin6=PG2
Mcu.Pin7=PC7
Mcu.Pin8=PA9
Mcu.Pin9=PA10
Mcu.PinsNb=21
Mcu.ThirdPartyNb=0
Mcu.UserConstants=
Mcu.UserName=STM32U575ZITxQ
MxCube.Version=6.3.0
MxDb.Version=DB.6.0.30
NVIC.BusFault_IRQn=true\:0\:0\:false\:false\:true\:false\:false
NVIC.DebugMonitor_IRQn=true\:0\:0\:false\:false\:true\:false\:false
NVIC.ForceEnableDMAVector=true
NVIC.HardFault_IRQn=true\:0\:0\:false\:false\:true\:false\:false
NVIC.MemoryManagement_IRQn=true\:0\:0\:false\:false\:true\:false\:false
NVIC.NonMaskableInt_IRQn=true\:0\:0\:false\:false\:true\:false\:false
NVIC.PendSV_IRQn=true\:0\:0\:false\:false\:true\:false\:false
NVIC.PriorityGroup=NVIC_PRIORITYGROUP_3
NVIC.SVCall_IRQn=true\:0\:0\:false\:false\:true\:false\:false
NVIC.SysTick_IRQn=true\:0\:0\:false\:false\:true\:false\:true
NVIC.UsageFault_IRQn=true\:0\:0\:false\:false\:true\:false\:false
PA10.GPIOParameters=GPIO_Speed,GPIO_PuPd,GPIO_Label
PA10.GPIO_Label=USART1_RX
PA10.GPIO_PuPd=GPIO_PULLDOWN
PA10.GPIO_Speed=GPIO_SPEED_FREQ_VERY_HIGH
PA10.Locked=true
PA10.Signal=USART1_RX
PA11.GPIOParameters=GPIO_Speed,GPIO_Label
PA11.GPIO_Label=USB_OTG_FS_DM
PA11.GPIO_Speed=GPIO_SPEED_FREQ_VERY_HIGH
PA11.Locked=true
PA11.Signal=USB_OTG_FS_DM
PA12.GPIOParameters=GPIO_Speed,GPIO_Label
PA12.GPIO_Label=USB_OTG_FS_DP
PA12.GPIO_Speed=GPIO_SPEED_FREQ_VERY_HIGH
PA12.Locked=true
PA12.Signal=USB_OTG_FS_DP
PA13\ (JTMS/SWDIO).Locked=true
PA13\ (JTMS/SWDIO).Mode=Trace_Asynchronous_SW
PA13\ (JTMS/SWDIO).Signal=DEBUG_JTMS-SWDIO
PA14\ (JTCK/SWCLK).Locked=true
PA14\ (JTCK/SWCLK).Mode=Trace_Asynchronous_SW
PA14\ (JTCK/SWCLK).Signal=DEBUG_JTCK-SWCLK
PA15\ (JTDI).GPIOParameters=GPIO_Label
PA15\ (JTDI).GPIO_Label=UCPD1_CC1
PA15\ (JTDI).Locked=true
PA15\ (JTDI).Signal=UCPD1_CC1
PA9.GPIOParameters=GPIO_Speed,GPIO_PuPd,GPIO_Label
PA9.GPIO_Label=USART1_TX
PA9.GPIO_PuPd=GPIO_PULLDOWN
PA9.GPIO_Speed=GPIO_SPEED_FREQ_VERY_HIGH
PA9.Locked=true
PA9.Signal=USART1_TX
PB14.GPIOParameters=GPIO_Label
PB14.GPIO_Label=UCPD_FLT
PB14.Locked=true
PB14.Signal=GPIO_Input
PB15.GPIOParameters=GPIO_Label
PB15.GPIO_Label=UCPD1_CC2
PB15.Locked=true
PB15.Signal=UCPD1_CC2
PB3\ (JTDO/TRACESWO).Locked=true
PB3\ (JTDO/TRACESWO).Mode=Trace_Asynchronous_SW
PB3\ (JTDO/TRACESWO).Signal=DEBUG_JTDO-SWO
PB5.GPIOParameters=GPIO_Label
PB5.GPIO_Label=UCPD_DBn
PB5.Locked=true
PB5.Signal=GPIO_Output
PB7.GPIOParameters=GPIO_Speed,GPIO_PuPd,GPIO_Label,GPIO_ModeDefaultOutputPP
PB7.GPIO_Label=LED_BLUE
PB7.GPIO_ModeDefaultOutputPP=GPIO_MODE_OUTPUT_PP
PB7.GPIO_PuPd=GPIO_PULLUP
PB7.GPIO_Speed=GPIO_SPEED_FREQ_HIGH
PB7.Locked=true
PB7.Signal=GPIO_Output
PC13.GPIOParameters=GPIO_Label,GPIO_ModeDefaultEXTI
PC13.GPIO_Label=USER_BUTTON
PC13.GPIO_ModeDefaultEXTI=GPIO_MODE_IT_FALLING
PC13.Locked=true
PC13.Signal=GPXTI13
PC14-OSC32_IN\ (PC14).Locked=true
PC14-OSC32_IN\ (PC14).Mode=LSE-External-Oscillator
PC14-OSC32_IN\ (PC14).Signal=RCC_OSC32_IN
PC15-OSC32_OUT\ (PC15).Locked=true
PC15-OSC32_OUT\ (PC15).Mode=LSE-External-Oscillator
PC15-OSC32_OUT\ (PC15).Signal=RCC_OSC32_OUT
PC2.GPIOParameters=GPIO_Label
PC2.GPIO_Label=VBUS_SENSE
PC2.Locked=true
PC2.Mode=IN3-Single-Ended
PC2.Signal=ADC1_IN3
PC7.GPIOParameters=GPIO_Speed,GPIO_PuPd,GPIO_Label
PC7.GPIO_Label=LED_GREEN
PC7.GPIO_PuPd=GPIO_PULLUP
PC7.GPIO_Speed=GPIO_SPEED_FREQ_HIGH
PC7.Locked=true
PC7.Signal=GPIO_Output
PG2.GPIOParameters=GPIO_Speed,GPIO_PuPd,GPIO_Label,GPIO_ModeDefaultOutputPP
PG2.GPIO_Label=LED_RED
PG2.GPIO_ModeDefaultOutputPP=GPIO_MODE_OUTPUT_PP
PG2.GPIO_PuPd=GPIO_PULLUP
PG2.GPIO_Speed=GPIO_SPEED_FREQ_HIGH
PG2.Locked=true
PG2.Signal=GPIO_Output
PinOutPanel.RotationAngle=0
ProjectManager.AskForMigrate=true
ProjectManager.BackupPrevious=false
ProjectManager.CompilerOptimize=6
ProjectManager.ComputerToolchain=false
ProjectManager.CoupleFile=false
ProjectManager.CustomerFirmwarePackage=
ProjectManager.DefaultFWLocation=true
ProjectManager.DeletePrevious=true
ProjectManager.DeviceId=STM32U575ZITxQ
ProjectManager.FirmwarePackage=STM32Cube FW_U5 V1.0.0
ProjectManager.FreePins=false
ProjectManager.HalAssertFull=false
ProjectManager.HeapSize=0x200
ProjectManager.KeepUserCode=true
ProjectManager.LastFirmware=true
ProjectManager.LibraryCopy=1
ProjectManager.MainLocation=Core/Src
ProjectManager.NoMain=false
ProjectManager.PreviousToolchain=
ProjectManager.ProjectBuild=false
ProjectManager.ProjectFileName=HelloWorld_nucleo-u575ziq.ioc
ProjectManager.ProjectName=HelloWorld_nucleo-u575ziq
ProjectManager.RegisterCallBack=
ProjectManager.StackSize=0x400
ProjectManager.TargetToolchain=STM32CubeIDE
ProjectManager.ToolChainLocation=
ProjectManager.UnderRoot=true
ProjectManager.functionlistsort=1-MX_GPIO_Init-GPIO-false-HAL-true,2-SystemClock_Config-RCC-false-HAL-false,3-MX_ADC1_Init-ADC1-false-HAL-true,4-MX_UCPD1_Init-UCPD1-false-LL-true,5-MX_USART1_UART_Init-USART1-false-HAL-true,0-MX_CORTEX_M33_NS_Init-CORTEX_M33_NS-false-HAL-true,0-MX_PWR_Init-PWR-false-HAL-true
RCC.CK48Freq_Value=48000000
RCC.CRSFreq_Value=48000000
RCC.DACCLockSelectionVirtual=RCC_DAC1CLKSOURCE_LSI
RCC.DACCLockSelectionVirtualString=RCC_DAC1CLKSOURCE_LSI
RCC.DACFreq_Value=32000
RCC.EPOD_VALUE=4000000
RCC.FDCANFreq_Value=258000000
RCC.FamilyName=M
RCC.HSE_VALUE=16000000
RCC.HSI48_VALUE=48000000
RCC.HSI_VALUE=16000000
RCC.IPParameters=CK48Freq_Value,CRSFreq_Value,DACCLockSelectionVirtual,DACCLockSelectionVirtualString,DACFreq_Value,EPOD_VALUE,FDCANFreq_Value,FamilyName,HSE_VALUE,HSI48_VALUE,HSI_VALUE,LSCOPinFreq_Value,LSIDIV_VALUE,LSI_VALUE,MSI_VALUE,PLL2PoutputFreq_Value,PLL2QoutputFreq_Value,PLL2RoutputFreq_Value,PLL3PoutputFreq_Value,PLL3QoutputFreq_Value,PLL3RoutputFreq_Value,PLLPoutputFreq_Value,PLLQoutputFreq_Value,PLLRCLKFreq_Value,RNGFreq_Value,SAI1Freq_Value,SAI2Freq_Value,SDMMCFreq_Value,USBFreq_Value,VCOInput2Freq_Value,VCOInput3Freq_Value,VCOInputFreq_Value,VCOOutputFreq_Value,VCOPLL2OutputFreq_Value,VCOPLL3OutputFreq_Value
RCC.LSCOPinFreq_Value=32000
RCC.LSIDIV_VALUE=32000
RCC.LSI_VALUE=32000
RCC.MSI_VALUE=4000000
RCC.PLL2PoutputFreq_Value=258000000
RCC.PLL2QoutputFreq_Value=258000000
RCC.PLL2RoutputFreq_Value=258000000
RCC.PLL3PoutputFreq_Value=258000000
RCC.PLL3QoutputFreq_Value=258000000
RCC.PLL3RoutputFreq_Value=258000000
RCC.PLLPoutputFreq_Value=258000000
RCC.PLLQoutputFreq_Value=258000000
RCC.PLLRCLKFreq_Value=258000000
RCC.RNGFreq_Value=48000000
RCC.SAI1Freq_Value=258000000
RCC.SAI2Freq_Value=258000000
RCC.SDMMCFreq_Value=258000000
RCC.USBFreq_Value=48000000
RCC.VCOInput2Freq_Value=4000000
RCC.VCOInput3Freq_Value=4000000
RCC.VCOInputFreq_Value=4000000
RCC.VCOOutputFreq_Value=516000000
RCC.VCOPLL2OutputFreq_Value=516000000
RCC.VCOPLL3OutputFreq_Value=516000000
SH.GPXTI13.0=GPIO_EXTI13
SH.GPXTI13.ConfNb=1
VP_PWR_VS_DBSignals.Mode=DisableDeadBatterySignals
VP_PWR_VS_DBSignals.Signal=PWR_VS_DBSignals
VP_PWR_VS_SECSignals.Mode=Security/Privilege
VP_PWR_VS_SECSignals.Signal=PWR_VS_SECSignals
VP_SYS_VS_Systick.Mode=SysTick
VP_SYS_VS_Systick.Signal=SYS_VS_Systick
board=NUCLEO-U575ZI-Q
boardIOC=true
isbadioc=false
`

**Comment by marco-polo-github** [comment]
And the cortex-m33 I just added like shown in the fotos:
![image](https://user-images.githubusercontent.com/32360080/130939801-1da3b95e-8595-46dd-84b7-03988781d4e4.png)
![image](https://user-images.githubusercontent.com/32360080/130939884-0e7ab3ee-aab2-462c-9d7a-4b22e05b039e.png)

But I can also make a PR if you want. (my first one with github ;-) )

**Comment by patrislav1** [comment]
I have made a bunch of updates - besides support for the new chips I also had to add support for "STM32CubeIDE" style of generated code (CubeMX doesn't support "Makefile" style project generation for L5 and U5 line of chips :roll_eyes:)

Please check with the new version and if you get it to work I'd be glad about a short feedback so I can include the chip/board into the list of tested targets.

**Comment by marco-polo-github** [comment]
(I have problems with my setup, and come back asap.)

**Comment by marco-polo-github** [comment]
It works, but the compiler flags used for cmake are different to the cubeIDE which results in different .bin files. Is there something I can adapt?

**Comment by patrislav1** [comment]
I observed the same compiler options / same `.bin` file size at least when comparing to a CubeMX generated Makefile project. (I don't use  STM32CubeIDE). However you can always use `target_compile_options` and `target_compile_definitions` in the main `CMakeLists.txt` to add more stuff. Or do you need to _remove_ stuff?

**Comment by patrislav1** [comment]
Closing this after half a year. Please reopen if you have new information
