### ISSUE TITLE
Use gitattributes to force native EOL

### ISSUE THREAD

**Issue by BenBE** [patrislav1/cubemx.cmake#5]
Please include a `.gitattributes` configuration in the main directory and ensure all files use native line endings in the repository:

```
*       text=auto
*.cmake text
*.in    text
*.md    text
*.py    text
```

Please convert line endings in the repository accordingly. TIA.

**Comment by patrislav1** [comment]
Fixed in 62b898d135769f4360294d2ff985e27cfa568e90
